In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/titanic dataset.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.shape

(891, 12)

In [4]:
null = pd.concat([df.isnull().sum()], axis=1, keys=['Null Values'])
null[null.sum(axis=1)>0]

Null Values
Age               177
Cabin             687
Embarked            2

In [5]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Cabin'] = df['Cabin'].fillna(df['Cabin'].mode()[0])
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [6]:
df['Pclass'] = df['Pclass'].astype('str')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null object
Name           891 non-null object
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          891 non-null object
Embarked       891 non-null object
dtypes: float64(2), int64(4), object(6)
memory usage: 83.7+ KB


In [8]:
df1 = pd.get_dummies(df[['Pclass','Name','Sex','Ticket','Cabin','Embarked']])

In [9]:
df.drop(df[['Pclass','Name','Sex','Ticket','Cabin','Embarked']], axis=1, inplace=True)

In [10]:
df = pd.concat([df, df1],axis=1)

In [11]:
df

PassengerId  Survived        Age  SibSp  Parch     Fare  Pclass_1  \
0              1         0  22.000000      1      0   7.2500         0   
1              2         1  38.000000      1      0  71.2833         1   
2              3         1  26.000000      0      0   7.9250         0   
3              4         1  35.000000      1      0  53.1000         1   
4              5         0  35.000000      0      0   8.0500         0   
..           ...       ...        ...    ...    ...      ...       ...   
886          887         0  27.000000      0      0  13.0000         0   
887          888         1  19.000000      0      0  30.0000         1   
888          889         0  29.699118      1      2  23.4500         0   
889          890         1  26.000000      0      0  30.0000         1   
890          891         0  32.000000      0      0   7.7500         0   

     Pclass_2  Pclass_3  Name_Abbing, Mr. Anthony  ...  Cabin_F G73  Cabin_F2  \
0           0         1                         0  ...            0         0   
1           0         0                         0  ...            0         0   
2           0         1                         0  ...            0         0   
3           0         0                         0  ...            0         0   
4           0         1                         0  ...            0         0   
..        ...       ...                       ...  ...          ...       ...   
886         1         0                         0  ...            0         0   
887         0         0                         0  ...            0         0   
888         0         1                         0  ...            0         0   
889         0         0                         0  ...            0         0   
890         0         1                         0  ...            0         0   

     Cabin_F33  Cabin_F38  Cabin_F4  Cabin_G6  Cabin_T  Embarked_C  \
0            0          0         0         0        0           0   
1            0          0         0         0        0           1   
2            0          0         0         0        0           0   
3            0          0         0         0        0           0   
4            0          0         0         0        0           0   
..         ...        ...       ...       ...      ...         ...   
886          0          0         0         0        0           0   
887          0          0         0         0        0           0   
888          0          0         0         0        0           0   
889          0          0         0         0        0           1   
890          0          0         0         0        0           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 1733 columns]

In [12]:
label = df.pop('Survived')

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=0.2)


# Random Forest

In [14]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [15]:
pred = rf.predict(X_test)
pred

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [16]:
from sklearn.metrics import roc_curve, auc

flase_positive, true_positive, thresholds = roc_curve(y_test, pred)
roc_auc = auc(flase_positive, true_positive)
roc_auc

0.7687233475479744

# Ada Boost

In [17]:
#ADA Boost

from sklearn.ensemble import AdaBoostClassifier

abc = AdaBoostClassifier()
abc.fit(X_train, y_train)

AdaBoostClassifier()

In [18]:
abc_pred = abc.predict(X_test)
abc_pred

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [19]:
false_positive, true_positive, thresold = roc_curve(y_test, abc_pred)
roc_auc = auc(false_positive, true_positive)
roc_auc

0.8061034115138593

In [20]:
#logistic regression include ADABoost

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(solver='liblinear')

In [21]:
abc1 = AdaBoostClassifier(base_estimator=lr)

In [22]:
abc1.fit(X_train,y_train)

AdaBoostClassifier(base_estimator=LogisticRegression(solver='liblinear'))

In [23]:
abc1_pred = abc1.predict(X_test) 

In [24]:
false_positive, true_positive, thresold = roc_curve(y_test, abc1_pred)
roc_auc = auc(false_positive, true_positive)
roc_auc

0.7553971215351812

# Gradient Boost

In [25]:
from sklearn.ensemble import GradientBoostingRegressor

In [39]:
gbr = GradientBoostingRegressor(learning_rate=0.15, max_depth=4)

In [40]:
gbr.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.15, max_depth=4)

In [41]:
gbr_pred = gbr.predict(X_test)

In [42]:
false_positive, true_positive, thresold = roc_curve(y_test, gbr_pred)
roc_auc = auc(false_positive, true_positive)
roc_auc

0.8433502132196162

In [30]:
features = gbr.feature_importances_

# Hyperparameters Tuning

In [34]:
from sklearn.model_selection import GridSearchCV

ht = {'max_depth':[3,4]}

tuning = GridSearchCV(estimator=GradientBoostingRegressor(), param_grid=ht, scoring='r2')
tuning.fit(X_train, y_train)
tuning.best_params_, tuning.best_score_

({'max_depth': 4}, 0.4626447978614707)

# Stacking

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import StackingClassifier

In [45]:
clf1 = KNeighborsClassifier(n_neighbors=3)
clf2 = RandomForestClassifier()
clf3 = GaussianNB()

In [48]:
stacking = StackingClassifier(estimators=[clf1,clf2,clf3], final_estimator=LogisticRegression())

In [52]:
from sklearn.model_selection import cross_val_score

for clf in [clf1,clf2,clf3]:
    cross_val_score(clf, X_train, y_train, scoring='accuracy')

array([0.70629371, 0.55944056, 0.64084507, 0.57042254, 0.59859155])